# Generated by Django 4.1.4 on 2023-10-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0000_init_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='address', unique=True, verbose_name='Адрес')),
                ('portSSH', models.CharField(max_length=5, verbose_name='SSH порт')),
                ('portWG', models.CharField(default=0, max_length=5, verbose_name='WG порт')),
                ('publicKey', models.CharField(default='public_key', max_length=50, unique=True, verbose_name='Публичный ключ')),
                ('statusServer', models.BooleanField(default=False, verbose_name='Статус активности сервера')),
                ('statusWG', models.BooleanField(default=False, verbose_name='Статус активности WG')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=60, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=60, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Серверный пользователь',
                'verbose_name_plural': 'Серверные пользователи',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=60, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=60, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Системный пользователь',
                'verbose_name_plural': 'Системные пользователи',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='address', max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('publicKey', models.CharField(default='public_key', max_length=50, unique=True, verbose_name='Публичный ключ')),
                ('allowedIps', models.CharField(default='10.0.0.1/32', max_length=18, verbose_name='Разрешенные IP')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
