# Generated by Django 4.1.4 on 2023-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='_id',
            field=models.CharField(default='server_', max_length=150, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='serveruser',
            name='_id',
            field=models.CharField(default='serveruser_', max_length=150, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='_id',
            field=models.CharField(default='systemuser_', max_length=150, unique=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.CharField(default='user_', max_length=150, unique=True, verbose_name='ID'),
        ),
    ]
