# Generated by Django 4.1.4 on 2023-12-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_server__id_serveruser__id_systemuser__id_user__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruser',
            name='_id',
            field=models.CharField(default='1', max_length=150, unique=True, verbose_name='ID'),
        ),
    ]
