# Generated by Django 4.1.4 on 2023-12-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_server__id_serveruser__id_systemuser__id_user__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.server', verbose_name='ID сервера'),
        ),
    ]
